#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
#include <math.h>

#ifndef __CONSTANTS_H__
#define __CONSTANTS_H__

#define NUMBER_OF_KERNELS 3
#define INITIAL_KERNEL_SIZE 3
#define KERNEL_MAX_SIZE (INITIAL_KERNEL_SIZE + 2 * (NUMBER_OF_KERNELS - 1))

//MUST BE EVEN
#define SIGNATURE_PADDING 16

#define HARRIS_KERNEL_SIZE 5

#define HARRIS_THRESHOLD_SIFT 70

#define HARRIS_THRESHOLD 50

#define INTEREST_THRESHOLD_INT 600

#define KERNEL_NON_MAX_SIZE 7

#define EDGE_AREA 3

#define BINARY_ZERO 0
#define BINARY_ONE 255

#define SIZE_X 240
#define SIZE_Y 240

#define SIGNATURE_LENGTH 128
#define LONG_INT_PER_SIGNATURE 2
#define MAX_SIGNATURES 150

#define INTERNAL_SECTORS 8

#define EXTERN_SECTORS 8

#define ORIENTATIONS 8

#define INTERNAL_SECTOR_SIZE 16

#define EXTERN_SECTOR_SIZE 14

#define INTERNAL_SIGNATURE_SIZE 64

#define EXTERN_SIGNATURE_SIZE 64

#define INTERNAL_SECTORS_PER_QUARTER 2

#define EXTERN_SECTORS_PER_QUARTER 2

#define SECTOR_SIZE 52

#define COS22_INT 92
#define SIN22_INT 38
#define SIN_COS45_256 181

#define MIN_INTRA_SIGNATURE_DISTANCE_BRIEF 10

#define MIN_INTRA_SIGNATURE_DISTANCE_SIFT 500

#define MAX_DISTANCE_SIFT 2000
#define MAX_DISTANCE_BRIEF 35
#define MAX_LOWES_RATIO 7


#define MAX_OBJECTS 10

#define MIN_INTEREST_SIZE 55

#define LEFT_OR_RIGHT_THRESHOLD 8

extern const uint8_t circle_sectors[SECTOR_SIZE][2];
extern const uint8_t internal_circle_sectors[INTERNAL_SECTORS_PER_QUARTER][INTERNAL_SECTOR_SIZE][2];
extern const uint8_t extern_circle_sectors[EXTERN_SECTORS_PER_QUARTER][EXTERN_SECTOR_SIZE][2];
extern const int8_t offsets[2][SIGNATURE_LENGTH][2];

#endif